### ISSUE TITLE
AISTATS camera-ready preparation

### ISSUE THREAD

**Issue by xukai92** [TuringLang/CoupledHMC.jl#1]
## To-Dos

Code

The repo is currently organised as a Julia package together with scripts located in `research` that produces the results in our paper. We will need to do some clean-ups before making things public.

- [x] Move `research/src/VecTarget.jl` into [a separate repo](https://github.com/xukai92/VecTargets.jl)
  - Can we merge it with `ChallengingPosteriorBenchmarks.jl` or so?
- [x] Update the kernel interface in `AdvancedHMC.jl`
- [x] Remove hacks (https://github.com/xukai92/CoupledHMC.jl/blob/master/src/CoupledHMC.jl#L14-L45) and adapt to the new kernel interface here
- [x] Remove deprecated files (e.g. `CoupledHMC2.jl`)

Some extra experiments

- [ ] Gaussians with increasing dimensionality
- [ ] Confirm meeting time with adapted NUTS parameters

Paper

The draft is almost there but we still need to finish the followings.

- [x] Trim down to the allowed number of pages~~
  - ~~@yebai We are currently at 8.5 pages. Do you think it's possible to ask if this length is allowed as camera-ready?~~
  - Now 9-page is allowed :tada:
  - Slight over 9-page ATM
- [x] Proofread the paper, especially proofs
- [x] Check all bib entries
- [x] Double check the new notation for coupled kernel from Tor
- [x] Include a link to this repo
- [ ] Also submit to arXiv

Please leave comments and feel free to add/edit bullet points here directly @yebai @torfjelde
